
workflows:
  android-workflow:
    name: ai_caption_generator (1)

    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter Pub Get
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - freefiretv581@gmail.com
